In [1]:
import cv2 as cv
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [19]:
image = keras.utils.load_img('P1.jpg',grayscale=True,target_size=(1500,1500))

In [20]:
image = np.array(image)
print(image.shape)

image.shape



(1500, 1500)


(1500, 1500)

In [21]:
cv.imshow('Test',image)
cv.waitKey(0)

-1

In [22]:
faces = cv.CascadeClassifier(
    cv.data.haarcascades + "haarcascade_frontalface_default.xml"
)
faces

< cv2.CascadeClassifier 00000225C9ACD690>

In [23]:
face = faces.detectMultiScale(image,scaleFactor=1.1,minNeighbors=1,minSize=(1,1))
face

array([[ 329,  675,   25,   25],
       [ 232,  394,   25,   25],
       [ 376,  416,   29,   29],
       [ 255,  761,   67,   67],
       [1072,  665,   62,   62],
       [  98,  951,   25,   25],
       [1131,  553,  101,  101],
       [ 424,  555,   92,   92],
       [ 947,  549,  103,  103],
       [ 274,  576,  101,  101],
       [1221,  376,   57,   57],
       [ 795,  508,   94,   94],
       [ 633,  531,   90,   90],
       [1129,  516,   26,   26],
       [ 945,  730,   48,   48],
       [ 444,  158,   62,   62],
       [ 919,  446,   30,   30],
       [ 478,  429,   37,   37],
       [ 976,  242,   39,   39],
       [ 449,  181,   51,   51],
       [ 484,  614,  116,  116],
       [ 289,   38,   62,   62],
       [ 492,  562,   75,   75],
       [ 886,  262,   60,   60]])

In [24]:
for (x,y,w,h) in face:
    print(x,y,w,h)
    cv.rectangle(image,(x,y),(x+w,y+h),(255,0,0))

329 675 25 25
232 394 25 25
376 416 29 29
255 761 67 67
1072 665 62 62
98 951 25 25
1131 553 101 101
424 555 92 92
947 549 103 103
274 576 101 101
1221 376 57 57
795 508 94 94
633 531 90 90
1129 516 26 26
945 730 48 48
444 158 62 62
919 446 30 30
478 429 37 37
976 242 39 39
449 181 51 51
484 614 116 116
289 38 62 62
492 562 75 75
886 262 60 60


In [25]:
cv.imshow('ClassifiedImage',image)
cv.waitKey()

-1

In [9]:
test_img = cv.imread('P5.jpg')
cv.imshow('image',test_img)
cv.waitKey()

-1

In [10]:
print(test_img)

[[[ 76  92  98]
  [ 74  90  96]
  [ 69  85  91]
  ...
  [164 174 162]
  [168 178 166]
  [139 149 137]]

 [[ 74  90  96]
  [ 70  86  92]
  [ 73  89  95]
  ...
  [114 124 112]
  [114 124 112]
  [101 111  99]]

 [[ 79  95 101]
  [ 74  90  96]
  [ 83 100 103]
  ...
  [ 88  98  86]
  [ 89  99  87]
  [ 98 108  96]]

 ...

 [[136 198 198]
  [138 200 200]
  [136 198 198]
  ...
  [149 217 210]
  [154 221 214]
  [156 223 216]]

 [[132 195 193]
  [129 192 190]
  [121 184 182]
  ...
  [103 174 164]
  [117 186 176]
  [117 186 176]]

 [[138 201 199]
  [131 194 192]
  [116 179 177]
  ...
  [ 87 158 148]
  [106 175 165]
  [101 170 160]]]


In [11]:
gray_test = cv.cvtColor(test_img,cv.COLOR_BGR2GRAY)

In [12]:
face = faces.detectMultiScale(gray_test)
face

array([[2398,    2,   53,   53],
       [2012,  191,   62,   62],
       [2140,  272,  236,  236],
       [2680,  270,  242,  242],
       [ 387,  314,  220,  220],
       [1335,  223,  209,  209],
       [2283,  248,  353,  353],
       [ 768,  271,  212,  212],
       [1763,  169,  230,  230],
       [3238,  626,   55,   55],
       [ 873,  762,   66,   66],
       [1138,  185,   89,   89]])

In [13]:
gray_test.shape

(1366, 3368)

In [ ]:
print('hello')